### ISSUE TITLE
Permitir emprestimo de multiplas chaves

### ISSUE THREAD

**Issue by masakik** [uspdev/empresta#25]
Havia mas foi desabilitado. Proposta colocar uma variavel no env que permita se for o caso.

**Comment by masakik** [comment]
Nesse caso, poderia na tela de empréstimo permitir digitar/escanear várias chaves ao mesmo tempo

**Comment by ricardfo** [comment]
@masakik, acho que esta issue pode ser fechada? Ela foi resolvida pelo commit [e3ccf79](https://github.com/uspdev/empresta/commit/e3ccf79189bd7d413fe0bcb15940b31a31815159)

**Comment by masakik** [comment]
só não implementei a possibilidade de adicionar multiplas chaves simultaneamente
