### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by kawanks** [uspdev/empresta#58]

**Comment by thiagogomesverissimo** [comment]
Não é melhor laravel 11.x?

**Comment by alecostaweb** [comment]
Sim, mas no momento estamos na versão 1 do cloudpanel.io que suporta até o php8.1. Por ora, podemos avançar para o Laravel 10 e assim que implementarmos nosso servidor de homologação com cloudpanel.io v2 (php7.1 até php8.3), vamos avançar com os sistemas em Laravel 11
