### ISSUE TITLE
Criar permissão para gerenciar categorias, materiais e cursos x departamentos de ensino

### ISSUE THREAD

**Issue by kawanks** [uspdev/empresta#69]
Atualmente a única permissão que é capaz de realizar essas ações é a permissão de `admin`. Todavia, há o perfil de pessoas que necessitam destas ações mas não devem ser capaz de mexer nas questões estruturais do sistema, como o sistema de gerenciamento de usuários do senhaunica-sociliate por exemplo. 

Se faz necessário assim um perfil intermediário entre o perfil `balcao` e o perfil `admin`.

**Comment by alecostaweb** [comment]
Somente para quem teria acesso aos demais cadastros.

Duas opções:
- Permissões da aplicação, por exemplo: Administrador ou outro nome 
- Permissões hierárquicas, por exemplo: poweruser ou boss

A permissão balcao continua com acesso apenas a empréstimo, devolução, cadastro de visitantes e listar os materiais
